from itertools import product
from snakemake.utils import format

GRID = {
    "nl":  [4, 5],
    "c":   [64, 128], 
    "nh":  [16, 32],
    "bs":  [64, 128], 
    "ded": [64, 128, 256],
    "cce": [0.05, 0.15, 0.25],
}

def make_id(cfg):
    return (f"nl{cfg['nl']}_c{cfg['c']}_nh{cfg['nh']}_bs{cfg['bs']}_ded{cfg['ded']}_cce{cfg['cce']}")

CONFIGS    = [dict(zip(GRID.keys(), v)) for v in product(*GRID.values())]
CONFIG_MAP = {make_id(c): c for c in CONFIGS}

CKPT_DIR = "checkpoints_pred16_hist32_{run_id}"

def ckpt(cfg, filename):
    return f"{CKPT_DIR.format(run_id=make_id(cfg))}/{filename}"

rule all:
    input:
        [ckpt(c, "gen_data.npy") for c in CONFIGS]

rule train_csdi:
    output:
        real       = CKPT_DIR.format(run_id="{run_id}") + "/real_data.npy",
        gen        = CKPT_DIR.format(run_id="{run_id}") + "/gen_data.npy",
        prediction = CKPT_DIR.format(run_id="{run_id}") + "/best_model.pt",
    log:
        CKPT_DIR.format(run_id="{run_id}") + "/training.log",
    params:
        nl  = lambda w: CONFIG_MAP[w.run_id]["nl"],
        c   = lambda w: CONFIG_MAP[w.run_id]["c"],
        nh  = lambda w: CONFIG_MAP[w.run_id]["nh"],
        bs  = lambda w: CONFIG_MAP[w.run_id]["bs"],
        ded = lambda w: CONFIG_MAP[w.run_id]["ded"],
        cce = lambda w: CONFIG_MAP[w.run_id]["cce"],
    shell:
        """
        mkdir -p checkpoints_pred16_hist32_{wildcards.run_id}
        python -u csdi_train_with_cat_final.py \
            --num_layer {params.nl} \
            --num_heads {params.nh} \
            --channels {params.c} \
            --num_head {params.nh} \
            --batch_size {params.bs} \
            --diffusion_embedding_dim {params.ded} \
            --cce_weight {params.cce} \
            > {log} 2>&1
        """