from itertools import product
from snakemake.utils import format

GRID = {
    "nl":  [2, 3], 
    "nc":  [160],
    "rc":  [32, 64], 
    "rl":  [2, 4, 6],
    "bs":  [256, 512],
    "d":   [0.1, 0.2],
    "cce": [0.15, 0.05, 0.25], 
}

def make_id(cfg):
    return (f"nl{cfg['nl']}_nc{cfg['nc']}_rc{cfg['rc']}_rl{cfg['rl']}"
            f"_bs{cfg['bs']}_d{cfg['d']}_cce{cfg['cce']}")

CONFIGS    = [dict(zip(GRID.keys(), v)) for v in product(*GRID.values())]
CONFIG_MAP = {make_id(c): c for c in CONFIGS}

CKPT_DIR = "checkpoints_pred16_hist32_{run_id}"

def ckpt(cfg, filename):
    return f"{CKPT_DIR.format(run_id=make_id(cfg))}/{filename}"

rule all:
    input:
        [ckpt(c, "gen_data.npy") for c in CONFIGS]

rule train_timegrad:
    output:
        real       = CKPT_DIR.format(run_id="{run_id}") + "/real_data.npy",
        gen        = CKPT_DIR.format(run_id="{run_id}") + "/gen_data.npy",
        prediction = CKPT_DIR.format(run_id="{run_id}") + "/prediction-net-state.pt",
    log:
        CKPT_DIR.format(run_id="{run_id}") + "/training.log",
    params:
        nl  = lambda w: CONFIG_MAP[w.run_id]["nl"],
        nc  = lambda w: CONFIG_MAP[w.run_id]["nc"],
        rc  = lambda w: CONFIG_MAP[w.run_id]["rc"],
        rl  = lambda w: CONFIG_MAP[w.run_id]["rl"],
        bs  = lambda w: CONFIG_MAP[w.run_id]["bs"],
        d   = lambda w: CONFIG_MAP[w.run_id]["d"],
        cce = lambda w: CONFIG_MAP[w.run_id]["cce"],
    shell:
        """
        mkdir -p checkpoints_pred16_hist32_{wildcards.run_id}
        python -u timegrad_train_with_cat_final.py \
            --num_layer         {params.nl} \
            --num_cell          {params.nc} \
            --residual_channels {params.rc} \
            --residual_layers   {params.rl} \
            --batch_size        {params.bs} \
            --dropout           {params.d} \
            --cce_weight        {params.cce} \
            > {log} 2>&1
        """